### ISSUE TITLE
Structure: Alias imports

### ISSUE THREAD

**Issue by danielbonifacio** [te-emprego/te-emprego#12]
Habilitar alias do Webapck

Para poder configurar, é necessário fazer o _eject_ das configurações.

- [x] Extrar `scripts` do _react-scripts_ `npm run eject`
- [x] Adicionar o diretório `config` aos _ignores_ do ESLint
- [x] Configurar os _aliases_ no arquivo do Webpack
- [x] Habilitar os _aliases_ no arquivo `jsconfig.json` para que a IDE reconheça
- [x] Refatorar todos os _imports_ para os _alias_, e não _relative paths_.

### Webpack:
As configurações do Webpack ficam disponíveis em `config/webpack.config.js`.

``` javascript
webpackConfig: {
  resolve: {
    alias: {
    alias: {
        'react-native': 'react-native-web',
        '@components': path.resolve(__dirname, '../src/components'),
        '@config': path.resolve(__dirname, '../src/config'),
        '@views': path.resolve(__dirname, '../src/views'),
        '@app': path.resolve(__dirname, '../src/App'),
        '@': path.resolve(__dirname, '../src')
      }
    }
  }
}
```

### JSConfig:
``` javascript
{
  "compilerOptions": {
    "target": "es2017",
    "allowSyntheticDefaultImports": false,
    "baseUrl": "./src",
    "paths": {
      "@components/*": ["./components/*"],
      "@config/*": ["./config/*"],
      "@views/*": ["./views/*"],
      "@app/*": ["./App/*"],
      "@/*": ["./*"]
    }
  },
  "exclude": ["node_modules", "build"]
}
```

**Comment by hugo-cardoso** [comment]
PR aberto.

#14

**Comment by danielbonifacio** [comment]
#14
