### ISSUE TITLE
Remover hash de modo desenvolvimento

### ISSUE THREAD

**Issue by msants** [te-emprego/te-emprego#19]
Seria interessante remover hash do webpack no modo desenvolvimento. 

![hash](https://user-images.githubusercontent.com/49846957/61572151-dd282c00-aa6f-11e9-816d-4eda27dadf5a.PNG)

**Comment by danielbonifacio** [comment]
@Schlickmann, consegue dar uma olhada nisso? Por mais que ache que seja do Styled Component, pode confirmar?

**Comment by Schlickmann** [comment]
@danielbonifacio irei olhar hoje depois do trabalho. :)

**Comment by Schlickmann** [comment]
Não acho que seja possível. Acredito que o styled-component tem essa funcionalidade para que uma estilização no component "Button" da "pagina 1"por exemplo não impacte o "Button" na "página 2".

Tentei procurar algum meio para fazer isso, mas acredito que nem sentido faça, pois em nenhum momento criamos/definimos um "className" essa tarefa é deixada nas "mãos" do styled-components.

![Captura de Tela 2019-07-22 às 7 46 51 PM](https://user-images.githubusercontent.com/11969565/61678977-84e46a80-acb9-11e9-90a4-0115dd2b62b5.png)

**Comment by danielbonifacio** [comment]
Realmente, não faz sentido remover essa feature.
