### ISSUE TITLE
Estrutura: Melhorias

### ISSUE THREAD

**Issue by danielbonifacio** [te-emprego/te-emprego#6]
Organizar a estrutura, separando estilos da logica.

**Comment by brunogcpinheiro** [comment]
Estava pensando em algo como, ex:

```js
components/Header/index.js => lógica
components/Header/styles.js => estilo
```
E os componentes globais, somente com estilo, como o Container em:

```js
components/global
```

**Comment by hugo-cardoso** [comment]
Fala Bruno! Estou seguindo mais ou menos essa linha.

https://github.com/te-emprego/te-emprego/tree/structure-improvements/src/components

**Comment by danielbonifacio** [comment]
Alguma atualização nessa issue, @hugo-cardoso?

**Comment by hugo-cardoso** [comment]
PR aberto @danielbonifacio. :)

#7

**Comment by danielbonifacio** [comment]
PR aprovado.
