### ISSUE TITLE
Code refacotr/beautify

### ISSUE THREAD

**Issue by danielbonifacio** [te-emprego/te-emprego#8]
Precisamos de padronizar o código:

  - [x] Instalar o ESLint (`standard` ou `airbnb`, **de preferência, sem semicolons**)
  - [x] Mover o padrão de importação de components de acordo com o informado na issue

### Padrão de components
Atualmente, os componentes precisam ser importados com redundância de código.
Exemplo: `import Header from '@components/Header/Header.component'`

A ideia é que ele possa ser importado via
`import Header from '@components/Header'`

**Comment by xavierleonardo** [comment]
@danielbonifacio, ainda não fiz nenhuma contribuição aqui mas quero ajudar. Gostaria de sugerir o _setup_ de estilo que eu uso (_standard_).

O que eu faço é usar o ESlint validando apenas sintaxe e erros, enquanto o _prettier_ fica responsável pela formatação.Desta forma, com o _husky_ eu crio um _hook_ de pré-_commit_ quechama o _lint-staged_ que executa o ESlint e o _prettier-stanard_.

Com isso, se houver algum problema no código, o _commit_ é cancelado. Do contrário o o código é formatado antes de ser "commitado".

O que acha?

**Comment by danielbonifacio** [comment]
Fala, @xavierleonardo!

Então, essa issue já tá sendo resolvida pela @Schlickmann. Da um follow no projeto aí, que a partir dessa semana agora vou soltar diversas issues.

Estamos preparando os ambientes e definindo patterns internos ainda.

Mas valeu pela disposição! Sua contribuição é sempre bem-vinda! 😄

**Comment by danielbonifacio** [comment]
Finalizada com o PR #10
